### ISSUE TITLE
v2.0.0.alpha1, 2.0 suggestion.

### ISSUE THREAD

**Issue by JuPlutonic** [hanami/validations#188]
52c1811f1e1bb4018d1cf878a6254b66de5ce404
is strongly connected to  'dry-validation', '~> 0.11.2', '< 0.12' in order to prevent dry-logic 0.5.0 installation.
I'm in hanami apps constantly dealing with outdated Dry::Monads::Either methods and deprecation warnings.
My suggestion is about how to overcome this problems in future 2.0 release.
I want to be assure what it is possible to decompose dry-logic incompatible calls to different methods so some methods wrapping «pre- dry-logic 0.5.0» logic and new written methods wrapping new current dry-logic.

**Comment by jodosha** [comment]
@JuPlutonic Thanks for your input.

Are you suggesting to change how internally `dry-validation` `0.11` to target `dry-logic` versions greater than `0.5`?

Is it your goal to avoid deprecation warnings or to make smoother the transition to 2.0?

**Comment by JuPlutonic** [comment]
Thanks. I didn't find how to get new methods worked from last dry-validation (their documentation topics have only three volumes: '0.13', '1.0', '1.3' and from my side I have to look into dry-validation commit history to understand some pieces of code), 
Now I see what dry-validation takes bucket of dependencies and my suggestion looks too naive and doesn't take into account version locks you now dealing with.

**Comment by jodosha** [comment]
@JuPlutonic Yeah, `hanami-validations` is locked to an old `dry-validation` version because of Semantic Versioning. We couldn't upgrade `hanami-validations` 1.x to the latest `dry-validation` without breaking backward compatibility.

That sucks, I know, but we value stability a lot.

To counterbalance this problem, the `hanami-validations` `2.0.0.alpha1` can be used in Hanami apps 1.x, **BUT** you'll still required to change the syntax.

For more details, please have a look at: http://hanamirb.org/blog/2019/07/26/announcing-hanami-validations-200alpha1.html
